class Solution {
        public int largestInteger(int[] nums, int k) {
                int n = nums.length;
                        
                                // Case 1: k == n
                                        // The array itself is the only subarray of size k.
                                                // Every element appears in exactly 1 subarray of size k.
                                                        if (k == n) {
                                                                    int maxVal = -1;
                                                                                for (int x : nums) {
                                                                                                maxVal = Math.max(maxVal, x);
                                                                                                            }
                                                                                                                        return maxVal;
                                                                                                                                }

                                                                                                                                        // Frequency array to count total occurrences of each number in nums
                                                                                                                                                int[] freq = new int[51];
                                                                                                                                                        for (int x : nums) {
                                                                                                                                                                    freq[x]++;
                                                                                                                                                                            }

                                                                                                                                                                                    // Case 2: k == 1
                                                                                                                                                                                            // Subarrays are single elements. We need the largest value that appears exactly once in nums.
                                                                                                                                                                                                    if (k == 1) {
                                                                                                                                                                                                                for (int i = 50; i >= 0; i--) {
                                                                                                                                                                                                                                if (freq[i] == 1) {
                                                                                                                                                                                                                                                    return i;
                                                                                                                                                                                                                                                                    }
                                                                                                                                                                                                                                                                                }
                                                                                                                                                                                                                                                                                            return -1;
                                                                                                                                                                                                                                                                                                    }

                                                                                                                                                                                                                                                                                                            // Case 3: 1 < k < n
                                                                                                                                                                                                                                                                                                                    // Any middle element (indices 1 to n-2) appears in at least 2 subarrays of size k.
                                                                                                                                                                                                                                                                                                                            // Only nums[0] and nums[n - 1] can potentially appear in exactly 1 subarray of size k.
                                                                                                                                                                                                                                                                                                                                    int res = -1;
                                                                                                                                                                                                                                                                                                                                            if (freq[nums[0]] == 1) {
                                                                                                                                                                                                                                                                                                                                                        res = Math.max(res, nums[0]);
                                                                                                                                                                                                                                                                                                                                                                }
                                                                                                                                                                                                                                                                                                                                                                        if (freq[nums[n - 1]] == 1) {
                                                                                                                                                                                                                                                                                                                                                                                    res = Math.max(res, nums[n - 1]);
                                                                                                                                                                                                                                                                                                                                                                                            }

                                                                                                                                                                                                                                                                                                                                                                                                    return res;
                                                                                                                                                                                                                                                                                                                                                                                                        }
                                                                                                                                                                                                                                                                                                                                                                                                        }
